### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-Dreamcast#2]
Di Gi Charat Fantasy (Japan).png
Doki Doki Idol Star Seeker Remix (Japan).png
Fragrance Tale (Japan).png
Illbleed (USA).png
Langrisser Millennium (Japan).png
Princess Holiday - Korogaru Ringo Tei Senya Ichiya (Japan).png
Reel Fishing - Wild (USA).png

![Di Gi Charat Fantasy (Japan)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/101521764-8b46b580-3986-11eb-9f8d-ba0927743020.png)
![Doki Doki Idol Star Seeker Remix (Japan)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/101521767-8c77e280-3986-11eb-88ac-67b417ec6ffe.png)
![Fragrance Tale (Japan)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/101521773-8da90f80-3986-11eb-94e3-ce9ca6a7049c.png)
![Illbleed (USA)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/101521775-8da90f80-3986-11eb-9e9f-7d6df5e39e4d.png)
![Langrisser Millennium (Japan)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/101521779-8e41a600-3986-11eb-9957-210a36977e46.png)
![Princess Holiday - Korogaru Ringo Tei Senya Ichiya (Japan)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/101521781-8eda3c80-3986-11eb-9d70-92cfca7690f5.png)
![Reel Fishing - Wild (USA)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/101521783-8f72d300-3986-11eb-95e8-44cbc2e05a5c.png)

**Comment by thebezelproject** [comment]
Updated.
